packages:
  # include packages in sub-folders (e.g. apps/ and packages/)
  - 'packages/**'
  - 'platform/**'
  - 'playgrounds/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!packages/firecamp-types'