const Constants = {
  ACTIONS: {
    UPDATE_DEFAULT_GBL_ENV: 'UPDATE_DEFAULT_GBL_ENV',
    UPDATE_DEFAULT_PRJ_ENV: 'UPDATE_DEFAULT_PRJ_ENV',
    UPDATE_GLOBAL_ENV_VARIABLES: 'UPDATE_GLOBAL_ENV_VARIABLES',
    UPDATE_PROJECT_ENV_VARIABLES: 'UPDATE_PROJECT_ENV_VARIABLES',
  },
};

export default Constants;
