export const APP_TYPES = {
  API: 'api',
  GRAPHQL: 'graphql',
};
export const UPDATE = {
  REQUEST: 'REQUEST',
  RAW_URL: 'RAW_URL',
  URL: 'URL',
  METHOD: 'METHOD',
  HEADERS: 'HEADERS',
  PARAMS: 'PARAMS',
  GRAPHQL_BODY: 'GRAPHQL_BODY',
  RESPONSE: 'RESPONSE',
  ACTIVE_AUTH: 'ACTIVE_AUTH',
  AUTH: 'AUTH',
  OAUTH2: 'OAUTH2',
  ADD_GRAPHQL_QUERY: 'ADD_GRAPHQL_QUERY',
  UPDATE_GRAPHQL_QUERY: 'UPDATE_GRAPHQL_QUERY',
  REMOVE_GRAPHQL_QUERY: 'REMOVE_GRAPHQL_QUERY',
  GRAPHQL_FILES: 'GRAPHQL_FILES',
  PLAYGROUND: 'PLAYGROUND',
  CURRENT_QUERY: 'CURRENT_QUERY',
};
export const STRINGS_QUERY_TYPES = {
  QUERY: 'Query',
  MUTATION: 'Mutation',
  SUBSCRIPTION: 'Subscription',
};

export const QUERY_TYPES = {
  QUERY: 'Q',
  SUBSCRIPTION: 'S',
  MUTATION: 'M',
};
export const BODY_TYPES = {
  GRAPHLQL_QUERIES: 'application/graphql',
};
